name: ASSC26
channels:
- defaults
- conda-forge
dependencies:
  - "python == 3.10" # somata>sorcery>executing has node finding error in 3.12
  - pip
  - matplotlib
  - numpy
  - scipy
  - jupyterlab
  - nodejs
  - ipympl
  - ipykernel
  - pip:
     - fooof
     - neurodsp
     - spectral_connectivity
     - somata
     - git+https://github.com/Eden-Kramer-Lab/Common_Oscillator_Models.git@python

